language: java
before_script:
- echo "Starting building"
script:
- mvn clean package
deploy:
  provider: heroku
  api_key:
   secure: grZM-FgjzG83kEuZdLXsOA
  app: kyrsovaya21
after_script:
- echo "Script finished"
after_success:
- echo "Build ready"
- ls -l $TRAVISE_BUILD_DIR/target
after_failure:
- echo "Build failure"
